spring:
    application:
        name: mall-gateway
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
        gateway:
            routes:
                - id: gateway-qq
                  uri: https://www.qq.com
                  predicates:
                    - Query=url,qq

                - id: gateway-baidu
                  uri: https://www.baidu.com
                  predicates:
                    - Query=url,baidu

server:
    port: 88